# Generated by Django 3.0.6 on 2020-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='all_votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
