# Generated by Django 3.0.6 on 2020-11-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_all_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='all_votes',
            field=models.IntegerField(default=0),
        ),
    ]
